name = "v2flare"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "bfd46ff0-7590-46fa-8a14-a03be0798d01"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
